after-startup-command = [
  'exec-and-forget borders active_color=0xff494d64 width=2.0',
]
start-at-login = true

# Start AeroSpace at login
# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or
# cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = true


[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = ['move-node-to-workspace Browse']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['move-node-to-workspace Browse']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['move-node-to-workspace Code']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace Code']

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = ['move-node-to-workspace Code']

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = ["move-node-to-workspace Code"]

[[on-window-detected]]
if.app-name-regex-substring = "dbeaver"
run = ["move-node-to-workspace Code"]

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['move-node-to-workspace Social']

[[on-window-detected]]
if.app-id = 'com.apple.Mail'
run = ['move-node-to-workspace Social']

[[on-window-detected]]
if.app-id = 'com.apple.Messages'
run = ['move-node-to-workspace Social']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace Social']

[[on-window-detected]]
if.app-id = 'com.linear'
run = ['move-node-to-workspace Organize']

# Floating Apps
[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'mirroring'
run = 'layout floating'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

alt-ctrl-f = 'fullscreen'
alt-ctrl-d = 'layout tiles'
alt-ctrl-a = 'layout accordion'

alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiling'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https:/wnikitabobko.github.io/AeroSpace/commands#workspace
alt-q = 'workspace Browse'
alt-w = 'workspace Social'
alt-e = 'workspace Organize'
alt-r = 'workspace Random'
alt-t = 'workspace Code'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-q = 'move-node-to-workspace Browse --focus-follows-window'
alt-shift-w = 'move-node-to-workspace Social --focus-follows-window'
alt-shift-e = 'move-node-to-workspace Organize --focus-follows-window'
alt-shift-r = 'move-node-to-workspace Random --focus-follows-window'
alt-shift-t = 'move-node-to-workspace Code --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-esc = ['flatten-workspace-tree', 'mode main']

#alt-shift-t = 'exec-and-forget open -a /Applications/Ghostty.app'
alt-shift-d = 'exec-and-forget open -a /Applications/DBeaver.app'
alt-shift-c = 'exec-and-forget open -a /Applications/chatGPT.app'
alt-shift-s = 'exec-and-forget open -a /Applications/Safari.app'
